"""empty message

Revision ID: 34706fee7238
Revises: c5b89d10785d
Create Date: 2022-12-11 00:41:13.687948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34706fee7238'
down_revision = 'c5b89d10785d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('exp_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('buyerName', sa.String(length=50), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('exp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience')
    # ### end Alembic commands ###
